### ISSUE TITLE
General ToDo list

### ISSUE THREAD

**Issue by MKegler** [phg17/sPyEEG#1]
Before branching this issue into specific subproblems here's a bunch of things that should be taken care of soonish
- [x] Move data to some other cloud drive (_Box_?). Cloning the repo takes a while now. See: https://github.com/phg17/sPyEEG/commit/5e0a1003e7a1fbe18823535aedc8d943319a4017
- [x] Add requirements to the README.md and some 'easy' setup for example requirements.txt for pip installation or 'requirements.yml' for conda. See: https://github.com/phg17/sPyEEG/commit/ff9d3080bca24b2164a8c4163463dce60c5c6371
- [x] Package the modules + add brief instructions on how to make install it (both normal and dev modes). See: https://github.com/phg17/sPyEEG/commit/58918e0d01320c9d7ff7b1afc237dcba95c24f5f
- [x] Split the main modules (```models.py``` has 2500 lines) into smaller chunks and try to sketch some module layout.
- [ ] Major cleanup. There are plenty of redundancies (a few classes share the same attributes and methods).
- [ ] ...
